import numpy as np

In [ ]:
arr= np.arange(20,31)

In [ ]:
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr[8]

28

In [ ]:
arr[2:7]

array([22, 23, 24, 25, 26])

In [ ]:
arr[2:7]=99

In [ ]:
arr

array([20, 21, 99, 99, 99, 99, 99, 27, 28, 29, 30])

In [ ]:
arr_c = arr.copy()

In [ ]:
arr_c

array([20, 21, 99, 99, 99, 99, 99, 27, 28, 29, 30])

In [ ]:
arr_2d= np.array([[6,4,2],[1,7,0],[3,5,8]])

In [ ]:
arr_2d

array([[6, 4, 2],
       [1, 7, 0],
       [3, 5, 8]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[1,1]

7

In [ ]:
arr_2d[2,1]

5

In [ ]:
arr

array([20, 21, 99, 99, 99, 99, 99, 27, 28, 29, 30])

In [ ]:
arr>30

array([False, False,  True,  True,  True,  True,  True, False, False,
       False, False])

In [ ]:
arr[arr>30]

array([99, 99, 99, 99, 99])

In [ ]:
arr[arr<30]

array([20, 21, 27, 28, 29])

In [ ]:
arr+arr

array([ 40,  42, 198, 198, 198, 198, 198,  54,  56,  58,  60])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr*arr

array([ 400,  441, 9801, 9801, 9801, 9801, 9801,  729,  784,  841,  900])

In [ ]:
arr*20

array([ 400,  420, 1980, 1980, 1980, 1980, 1980,  540,  560,  580,  600])

In [ ]:
arr/7

array([ 2.85714286,  3.        , 14.14285714, 14.14285714, 14.14285714,
       14.14285714, 14.14285714,  3.85714286,  4.        ,  4.14285714,
        4.28571429])

In [ ]:
arr

array([20, 21, 99, 99, 99, 99, 99, 27, 28, 29, 30])

In [ ]:
np.sqrt(arr)

array([4.47213595, 4.58257569, 9.94987437, 9.94987437, 9.94987437,
       9.94987437, 9.94987437, 5.19615242, 5.29150262, 5.38516481,
       5.47722558])

In [ ]:
arr.shape

(11,)

In [ ]:
np.exp(arr)

array([4.85165195e+08, 1.31881573e+09, 9.88903032e+42, 9.88903032e+42,
       9.88903032e+42, 9.88903032e+42, 9.88903032e+42, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13])

In [ ]:
np.log(arr)

array([2.99573227, 3.04452244, 4.59511985, 4.59511985, 4.59511985,
       4.59511985, 4.59511985, 3.29583687, 3.33220451, 3.36729583,
       3.40119738])

# Pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
lable = ['a','b','c']

In [ ]:
my_data = [10,34,29]

In [ ]:
arr = np.array([23,45,67])

In [ ]:
d = {'x':78, 'y':89, 'z':78}

# Series (contain only 1 col)

In [ ]:
pd.Series(data=my_data)

0    10
1    34
2    29
dtype: int64

In [ ]:
pd.Series(my_data)

0    10
1    34
2    29
dtype: int64

In [ ]:
my_data

[10, 34, 29]

In [ ]:
s1=pd.Series(my_data)

In [ ]:
s1

0    10
1    34
2    29
dtype: int64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
s1

0    10
1    34
2    29
dtype: int64

In [ ]:
pd.Series(my_data,index=lable)

a    10
b    34
c    29
dtype: int64

In [ ]:
pd.Series(arr)

0    23
1    45
2    67
dtype: int32

In [ ]:
pd.Series(arr,lable)

a    23
b    45
c    67
dtype: int32

In [ ]:
pd.Series(my_data,lable)

a    10
b    34
c    29
dtype: int64

In [ ]:
pd.Series(d)

x    78
y    89
z    78
dtype: int64

In [ ]:
pd.Series([45,67,69],['dany','ram','sonu'])

dany    45
ram     67
sonu    69
dtype: int64

In [ ]:
pd.Series([500,23,45,25,155])

0    500
1     23
2     45
3     25
4    155
dtype: int64

# Dataframe

In [ ]:
ad = np.random.randn(4,4)

In [ ]:
ad

array([[-0.02418393, -0.60905014,  0.94334897, -0.00305346],
       [ 0.731237  ,  0.61191524, -0.22043677, -0.81537683],
       [-0.50645633,  1.1618902 ,  0.22262805,  0.64502711],
       [ 0.67564697, -0.27658277, -0.22975748, -1.64621246]])

In [ ]:
df = pd.DataFrame(ad)

In [ ]:
df

0         1         2         3
0 -0.024184 -0.609050  0.943349 -0.003053
1  0.731237  0.611915 -0.220437 -0.815377
2 -0.506456  1.161890  0.222628  0.645027
3  0.675647 -0.276583 -0.229757 -1.646212

In [ ]:
data1 = np.random.randn(5,5)

In [ ]:
data1

array([[ 1.01933714, -0.50459561,  1.09780156,  0.11501005, -1.02348277],
       [-1.28944773, -0.65061898, -0.66956735, -0.97769431, -1.04069785],
       [-1.06335598,  1.1357835 , -0.72305439, -0.24601602,  0.93163442],
       [ 0.84125721, -0.00264595,  1.40604162, -0.01890542, -1.80737875],
       [ 0.97535708,  0.09264861,  0.26489684, -0.41591576, -0.90788894]])

In [ ]:
df1 = pd.DataFrame(data1,columns=['ravi','avi','sara','janu','babu'])

In [ ]:
df1

ravi       avi      sara      janu      babu
0  1.019337 -0.504596  1.097802  0.115010 -1.023483
1 -1.289448 -0.650619 -0.669567 -0.977694 -1.040698
2 -1.063356  1.135784 -0.723054 -0.246016  0.931634
3  0.841257 -0.002646  1.406042 -0.018905 -1.807379
4  0.975357  0.092649  0.264897 -0.415916 -0.907889

In [ ]:
df2 = pd.read_csv('Position_Salaries.csv')


In [ ]:
df2

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000